---
- name: Ensure SSH keys exist and are added to authorized keys
  hosts: all
  become: true
  tasks:

    - name: Check if SSH private key exists
      stat:
        path: /root/.ssh/id_rsa
      register: ssh_key

    - name: Generate SSH key pair if missing
      command: ssh-keygen -t rsa -b 4096 -f /root/.ssh/id_rsa -N ""
      when: not ssh_key.stat.exists

    - name: Ensure .ssh directory has correct permissions
      file:
        path: /root/.ssh
        state: directory
        mode: "0700"

    - name: Ensure private key has correct permissions
      file:
        path: /root/.ssh/id_rsa
        state: file
        mode: "0600"
      when: ssh_key.stat.exists

    - name: Ensure public key has correct permissions
      file:
        path: /root/.ssh/id_rsa.pub
        state: file
        mode: "0644"
      when: ssh_key.stat.exists

    - name: Add public key to authorized_keys
      authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
