- name: System Health Check
  hosts: ubuntu
  become: yes
  tasks:
    - name: Create a directory for health check logs
      file:
        path: /var/log/system-health
        state: directory
        mode: '0755'
        owner: root
        group: root
      become: yes

    - name: Create a system health check script
      copy:
        dest: /usr/local/bin/system_health.sh
        content: |
          #!/bin/bash
          LOG_DIR="/var/log/system-health"
          LOG_FILE="$LOG_DIR/report-$(TZ='America/New_York' date '+%Y-%m-%d_%H-%M-%S').txt"
          COMBINED_FILE="$LOG_DIR/combined.txt"

          mkdir -p "$LOG_DIR"

          HOSTNAME=$(hostname)
          DATE=$(TZ='America/New_York' date '+%Y-%m-%d %H:%M:%S')

          echo "===================================" > $LOG_FILE
          echo "     System Health Report - $HOSTNAME - $DATE" >> $LOG_FILE
          echo "===================================" >> $LOG_FILE
          echo "" >> $LOG_FILE

          # CPU Usage
          echo "CPU Usage:" >> $LOG_FILE
          top -bn1 | grep "Cpu(s)" >> $LOG_FILE
          echo "" >> $LOG_FILE

          # Memory Usage
          echo "Memory Usage:" >> $LOG_FILE
          free -h >> $LOG_FILE
          echo "" >> $LOG_FILE

          # Disk Usage
          echo "Disk Usage:" >> $LOG_FILE
          df -h >> $LOG_FILE
          echo "" >> $LOG_FILE

          # Network Interfaces and IPs
          echo "Network Interfaces and IPs:" >> $LOG_FILE
          ip -brief addr show >> $LOG_FILE
          echo "" >> $LOG_FILE

          # Running Processes
          echo "Top 5 Running Processes by Memory Usage:" >> $LOG_FILE
          ps aux --sort=-%mem | awk 'NR<=6{print $0}' >> $LOG_FILE
          echo "" >> $LOG_FILE

          # Uptime
          echo "System Uptime:" >> $LOG_FILE
          uptime >> $LOG_FILE
          echo "" >> $LOG_FILE

          # Last Login
          echo "Last Logins:" >> $LOG_FILE
          last -n 5 >> $LOG_FILE
          echo "" >> $LOG_FILE

          # Active Users
          echo "Active Users:" >> $LOG_FILE
          who >> $LOG_FILE
          echo "" >> $LOG_FILE

          # Failed Systemd Services
          echo "Failed Systemd Services:" >> $LOG_FILE
          systemctl list-units --failed >> $LOG_FILE
          echo "" >> $LOG_FILE

          # Combine last 5 log files into a single file
          ls -t "$LOG_DIR"/report-* | head -n 5 | xargs cat > "$COMBINED_FILE"

          echo "✅ System health report saved to: $LOG_FILE"
          echo "✅ Combined log file created at: $COMBINED_FILE"
        mode: '0755'
      become: yes

    - name: Execute the system health check script immediately on creation
      shell: "/usr/local/bin/system_health.sh >> /var/log/system-health/immediate-run.log 2>&1"
      become: yes
      become_user: root

    - name: Schedule a cron job to run the script daily at midnight
      cron:
        name: "System Health Check"
        job: "/usr/local/bin/system_health.sh"
        minute: "0"
        hour: "0"

    - name: Verify the cron job is scheduled
      cron:
        name: "System Health Check"
        state: present
        job: "/usr/local/bin/system_health.sh"

